name: Checkout
on: [push]

jobs:
    checkout-and-diisplay-files:
        runs-on: ubuntu-latest
        steps:
          - name: List Fles Berfore Checkout
            run: ls -a
          - name: Checkout
            run: |
              git init
              git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
              git fetch origin
              git checkout main
          - name: List Fles After Checkout
            run: ls -a