name: Checkout
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
        - name: List Fles Berfore Checkout
          run: ls -a
        - uses: actions/checkout@v3
        - name: List Fles After Checkout
          run: ls -a  